{{- if .Values.gateway.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-gateway
  annotations:
    {{- toYaml .Values.gateway.ingress.annotations | nindent 4 }}
spec:
  {{- if .Values.gateway.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.gateway.ingress.host }}
      secretName: {{ .Release.Name }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.gateway.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-gateway
                port:
                  number: {{ .Values.gateway.port }}
{{- end }}
